### ISSUE TITLE
v0.7 incompatible with Ember <= v3.5

### ISSUE THREAD

**Issue by jonnygreen** [ember-animation/ember-animated#146] opened 2019-08-06 14:11 UTC
**Describe the bug**
The changes to `animated-container` introduced by PR #139 are incompatible with versions of Ember 3.5 or less (and possibly later, though this is as late as I tested).

The `animated-container` component (nor anything it `yield`s) no longer renders after updating to 0.7.

**To Reproduce**
1. Visit https://codesandbox.io/s/ember-animated-test-35-3dck8 (3.5 Ember app)
1. Click on 'Show'
1. Observe 'Hello World! does not appear

![3 5](https://user-images.githubusercontent.com/95841/62546808-19bf9a00-b85c-11e9-950b-ff70e4e809df.gif)

**Expected behaviour**
1. Visit https://codesandbox.io/s/ember-animated-test-39-rgskl (3.9 Ember app with the same code)
1. Click on 'Show'
1. Observe 'Hello World!' does appear

![3 9](https://user-images.githubusercontent.com/95841/62546821-1f1ce480-b85c-11e9-8ea7-b4c4f87cb18c.gif)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Comment by ef4** [comment] 2019-08-06 15:12
Hmm, that PR does use some newer features but it polyfills them and the polyfills are tested back to at least 3.4-lts. Not sure yet what's happening here.

@ryanto if you have a chance to look at this before me it would be appreciated.

**Comment by jonnygreen** [comment] 2019-08-07 16:25
This looks to be an issue with `ember-element-helper` and `...attributes`. Ember 3.5 is not rendering the tag with `...attributes` - see https://github.com/tildeio/ember-element-helper/issues/6

**Comment by ryanto** [comment] 2019-08-08 03:31
Yikes! 

@jonnygreen Yup, I can confirm that the `ember-element-helper` does not work with `ember-source` `3.5` or `3.6`. It does work with Ember `3.4` and `~3.7.2`, so if you can upgrade or downgrade to one of those versions, or any version beyond, that might help you get unstuck today!

@ef4 I spent some time trying to track this down and it looks like [3.7.2](https://github.com/emberjs/ember.js/releases/tag/v3.7.2) has some glimmer upgrades that fix the issue. I'm able to reproduce in the bug with element-helper in `3.5 - 3.7.1`... I'll share some code over in https://github.com/tildeio/ember-element-helper/issues/6

In the mean time, what's the best way for ember-animated to deal with this?

* Should I wait to see what happens with element-helper? Maybe it's possible to patch release the glimmer updates to the 3.5 and 3.6 lines? This is above my pay grade :)

* I could add a check in AnimatedContainer's template and only use `element-helper` if the tag is not `div`. It's hacky, but it adds the old code path back to the project.

Happy to push this forward, just need a little direction.

**Comment by chancancode** [comment] 2020-04-30 08:21
This is fixed on the Ember side for all currently supported versions. The fix was even back ported to 3.4 LTS, but supported for 3.4 has already been dropped here. Probably can be closed now.

**Closed** 2020-04-30 15:55 UTC
